all:
	python process_jobs.py ../../../Dataset/splitjobs/jobs1.tsv win1_Jobs.tf_only ../1_apps/train_jobs_index ../1_apps/test_jobs_index

cp:
	cp *_Y ../win1

clean:
	rm -rf *.pyc train_jobs_index test_jobs_index train_Y test_Y *.log
