all:
	python process_users.py ../../../Dataset/users.tsv ../1_apps/train_users_index ../1_apps/test_users_index

cp:
	cp *_X ../win1

clean:
	rm -rf *.pyc train_users_index test_users_index train_X test_X *.log
