#!/usr/bin/python2.7
############################################################
##  FILENAME:   extractHTMLTxt.py    
##  VERSION:    1.0
##  SINCE:      2014-03-01
##  AUTHOR: 
##      Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
##
############################################################
##  Edited by MacVim
##  Documentation auto-generated by Snippet 
############################################################

import csv
import sys
from HTMLParser import HTMLParser
from util import *

inFile = sys.argv[1]

with open(inFile) as input:
	text = zip(*(line.strip().split('\t') for line in input))
	text = text[3]
	text = text[1:len(text)-1]
	#print text

output = ["" for n in range(len(text))]
output_file = open('htmls.' + inFile , 'w')

nTexts = len(text)
print "nTexts (nJobs): ", nTexts
pb = ProgressBar(nTexts, 50)    

for i in range (0, nTexts-1):
    try:
        output[i] = strip_tags(text[i])
    except:
        continue
	
	for word in delete_list:
		output[i] = output[i].replace(word, "")

	print output[i]
	output_file.write("%s\n" % output[i])

    pb.update(i)
    pb.display()
