############################################################
##    FILENAME:   extractJobwithJobID.py    
##    VERSION:    1.0
##    SINCE:      2014-05-20
##    AUTHOR: 
##        Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
##
############################################################
##    Edited by MacVim
##    Documentation auto-generated by Snippet 
############################################################

import sys
import csv
csv.field_size_limit(sys.maxsize)

def next_job (reader, JOBID_IDX=0):
    try:
        job_cur = reader.next()
    except:
        return reader, None, None, False

    if job_cur is not None:
        jobid = int(job_cur[JOBID_IDX])
        return reader, job_cur, jobid, True
    else:
        return reader, job_cur, None, False

if __name__ == "__main__":
    job1 = csv.reader(open("../Dataset/splitjobs/jobs1.tsv", "r"), \
                      delimiter="\t")
    jobidx = csv.reader(open("./sampleData/sampled_jobs_id.tsv", "r"))
    
    outfile = open("./sampleData/sampled_jobs.tsv", "w+")

    # ignore header
    JOBID_IDX = 0
    header1 = job1.next()
    header2 = jobidx.next()
    print header1, header2
    outfile.write("\t".join(header1) + "\n")
    # now content
    job_cur = job1.next()
    job1id = int(job_cur[JOBID_IDX])
    jobidxid = int(jobidx.next()[JOBID_IDX])
    success = True
    a = 0
    b = 0
    c = 0
    while success:
        if job1id == jobidxid:
            outfile.write("\t".join(job_cur) + "\n")
            job1, job_cur, job1id, success = next_job(job1)
            jobidx, _, jobidxid, success2 = next_job(jobidx)
            success = success and success2
            a += 1
        elif job1id < jobidxid:
            job1, job_cur,job1id, success = next_job(job1)
            b += 1
        elif job1id > jobidxid:
            print job1id, jobidxid
            jobidx, _, jobidxid, success = next_job(jobidx)
            c += 1

    print a, b, c
