############################################################
##    FILENAME:   process_apps.py    
##    VERSION:    1.0
##    SINCE:      2014-08-17
##    AUTHOR: 
##        Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
##
############################################################
##    Edited by MacVim
##    Documentation auto-generated by Snippet 
############################################################

'''
INPUT: 
  1. application records
  2. user index file
  3. job index file
OUTPUT: 
  1. sparse matrix A
'''
import sys
import csv

NARGS = 5
WIN_ONE_ONLY = True
def usage():
    ustr = 'Usage: \n'
    ustr += '  process_apps.py [user_index_file] [job_index_file] [app_file] [A_file]'
    sys.stderr.write(ustr + '\n')

def output(job_mat_ids, user_mat_id, A_writer):
    # sort job_mat_ids
    job_mat_ids.sort()
    # form string
    string = str(user_mat_id)
    for jmid in job_mat_ids:
        string += " " + str(jmid) + ":1"
    A_writer.write(string+'\n')

if __name__ == '__main__':
    # validate the input
    nargs = len(sys.argv)
    if nargs < NARGS:
        usage()
    user_file = sys.argv[1]
    job_file = sys.argv[2]
    app_file = sys.argv[3]
    A_file = sys.argv[4]

    # read user 
    user_reader = open(user_file, 'rb')
    user_lookup = {} # user index -> matrix index
    mat_index = 0
    for line in user_reader:
        if line == 'UserID': continue
        user_index = int(line.strip('\n'))
        if not user_lookup.has_key(user_index):
            user_lookup.update({user_index:mat_index})
            mat_index += 1
        else:
            sys.stderr.write('ERROR: continuous user index\n')
    user_reader.close()
    
    # read job
    job_reader = open(job_file, 'rb')
    job_lookup = {} # job index -> matrix index
    mat_index = 0
    for line in job_reader:
        if line == 'JobID': continue
        job_index = int(line.strip('\n'))
        if not job_lookup.has_key(job_index):
            job_lookup.update({job_index:mat_index})
            mat_index += 1
        else:
            sys.stderr.write('ERROR: continuous job index\n')
    job_reader.close()
    
    # read app
    app_reader = open(app_file, 'rb')
    app_reader = csv.reader(app_reader, delimiter='\t')
    header = app_reader.next()
    A_writer = open(A_file, 'wb')
    user = []
    user_index_cache = -1
    for app in app_reader:
        user_id = int(app[0])
        job_id = int(app[-1])
        window_id = int(app[1])
        if window_id > 1 and WIN_ONE_ONLY: 
            continue
        if not user_lookup.has_key(user_id):
            sys.stderr.write('app_file ERROR: no given user\n')
        if not job_lookup.has_key(job_id):
            sys.stderr.write('app_file ERROR: no given job\n')
        #print user_lookup[user_id], job_lookup[job_id]
        user_mat_id = user_lookup[user_id]
        job_mat_id = job_lookup[job_id]
        if user_id == user_index_cache: # existing user
            job_mat_id = job_lookup[job_id]
            user.append(job_mat_id)
        elif user_index_cache < 0: # first new user
            user.append(job_mat_id)
            user_index_cache = user_id
        else: # non-first new user
            output (user, user_index_cache, A_writer)
            user = []
            user.append(job_mat_id)
            user_index_cache = user_id
    if len(user) > 0:
        output (user, user_index_cache, A_writer)
    A_writer.close()
