############################################################
##    FILENAME:   util.py    
##    VERSION:    1.0
##    SINCE:      2014-05-06
##    AUTHOR: 
##        Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
##
############################################################
##    Edited by MacVim
##    Documentation auto-generated by Snippet 
############################################################

from HTMLParser import HTMLParser

class MLStripper(HTMLParser):
	def __init__(self):
		self.reset()
		self.fed = []
	def handle_data(self, d):
		self.fed.append(d)
	def get_data(self):
		return ''.join(self.fed)

def strip_tags(htmlstr):
    """
    Remove all html tags
    """
	s = MLStripper()
	s.feed(htmlstr)
	return s.get_data()

def strip_escapse(string):
    """
    Remove all unexpected escape
    """
    delete_list = ["\\r", "\\n", "\\r\\n", "\\t", "\\\r", "\\\n"]
    
    tmp = string
    for escape in delete_list:
        tmp = tmp.strip(escape)

    return tmp
